name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  foo: # change this
    required: true
    description: 'input description here'
runs:
  using: 'node16'
  main: 'dist/index.js'
